### ISSUE TITLE
Design Discussion and Review

### ISSUE THREAD

**Issue by copejon** [yard-turkey/lib-bucket-provisioner#2]
This issue is to be the primary thread for early design dialogue.

**Comment by jeffvance** [comment]
@bassam believes a centralized bucket controller is a better design.

**Comment by jeffvance** [comment]
Here's a comment block to discuss a centralized controller:
1, where does it live?
1. a plus is each provisioner can have lesser permissions, only central controller needs full access.
1. differs from k8s external provisioning where each provisioner is essentially its own controller.
1.

**Comment by jeffvance** [comment]
Here's a comment block to discuss binding and topology aware binding:
First, in this context, _binding_ refers to scheduling an app pod on a node that best meets the constraints (if any) of the pod's PVs. This is very different from the use of _binding_ to refer to the "connection" or mapping of a PV and a PVC. 

The use of _binding_ in the main README file means OB <-> OBC binding only -- nothing to do with node/topology binding. There are likely some use cases where topology aware pod <-> node binding is beneficial but we'd like to defer this to a later phase of bucket provisioning.

**Comment by jeffvance** [comment]
Issues and/or PRs against the design doc are the going forward way to discuss/address design feedback.
