### ISSUE TITLE
define Delete and Revoke wrt reclaimPolicy

### ISSUE THREAD

**Issue by jeffvance** [yard-turkey/lib-bucket-provisioner#64]
The current design is to call the `Delete` method only for new buckets (greenfield) with a reclaimPolicy of "Delete". All other cases call `Revoke`.

The problem with this is that provisioners cannot distinguish between `Revoke` called on a greenfield bkt's delete vs called for any brownfield bkt, regardless of its reclaimPolicy. And, perhaps, some provisioners will want to distinguish these two cases.

We could change the design such that  `Delete` is always called when the reclaimPolicy == "Delete" and `Revoke` is always called when the reclaimPolicy == "Retain". And provisioners _should_ delete the bkt when `Delete` is called, even if it was a brownfield. bkt. If this is not the desired behavior then the storage class's reclaimPolicy should not be "delete".

This approach keeps the library neutral on greenfield vs. brownfield and relies simply on the reclaim policy.

**Comment by copejon** [comment]
Per our call - it's agreed that protecting static buckets from accidental deletion is the preferred course of action.  This means that a field indicating whether it was a dynamically provisioned bucket or a static bucket will override the reclaim policy.  

If the bucket is static, reclaim policy of Delete & Erase should be ignored and instead credentials should only be Revoked.

cc @jeffvance before I close, can you TAL to see if you agree?

**Comment by jeffvance** [comment]
Agree with concerns.
