### ISSUE TITLE
missing documentation on how to build and run a provisioner

### ISSUE THREAD

**Issue by dannyzaken** [yard-turkey/lib-bucket-provisioner#91]
when working on NooBaa provisioner it would have been helpful if there were more technical documentation and examples regarding the provisioner build.
1. how to build and run the provisioner locally (dev mode)
2. how to build a Docker image (an example dockerfile)
3. what are the permissions required by the provisioner when running in k8s (example yaml)

**Comment by screeley44** [comment]
@dannyzaken @erinaboyd @jeffvance @copejon 

See if this satisfies this a bit better...

Link from main lib [README.md](https://github.com/yard-turkey/lib-bucket-provisioner)
```
Provisioner Developers should look <link>here</link> for some guidance/recommendations/tips on how to get started with creating your own Provisioner.
```

that link points to this [doc](https://github.com/yard-turkey/examples-and-blogs/blob/master/examples/sample-how-to-write-provisioner.md)

We also have additional examples (including on how to run and test)
[aws-s3-provisioner README](https://github.com/yard-turkey/aws-s3-provisioner)
[examples](https://github.com/yard-turkey/examples-and-blogs/tree/master/examples)

**Comment by dannyzaken** [comment]
Thanks, looks great. very helpful

**Comment by dannyzaken** [comment]
sorry, closed by mistake. in any case it looks much better now. decide if you want to close it

**Comment by jeffvance** [comment]
Closed via above links
