### ISSUE TITLE
OBC updates ignored once bucket is provisioned

### ISSUE THREAD

**Issue by jeffvance** [yard-turkey/lib-bucket-provisioner#95]
This is for public FYI:
Today, once a bucket is provisioned all subsequent OBC updates are ignored. The implications of this are changes in (future) bucket properties such as ACL, size limits, etc won't be processed by  the lib.

**Comment by copejon** [comment]
we should add this to the design doc

**Comment by jeffvance** [comment]
#97 addresses this.
